/** Field synonym tables and profile-key inference patterns. */

import type { UserData } from "@/shared/types";

export const AUTOCOMPLETE_KEY: Record<string, keyof UserData> = {
  name: "name",
  "given-name": "firstName",
  "family-name": "lastName",
  email: "email",
  tel: "phone",
  "tel-national": "phone",
  "tel-local": "phone",
  "street-address": "address",
  "address-line1": "address",
  "address-level2": "city",
  "address-level1": "state",
  "postal-code": "zipCode",
  country: "country",
  "country-name": "country",
  url: "portfolio",
  "organization-title": "currentRole",
  bday: "dateOfBirth",
};

export const SYNONYMS: Record<string, string[]> = {
  // Personal
  firstName: ["first name", "given name", "forename"],
  lastName: ["last name", "surname", "family name"],
  name: [
    "name",
    "full name",
    "your name",
    "applicant name",
    "legal name",
    "full legal name",
    "complete name",
  ],
  email: [
    "email",
    "e-mail",
    "mail id",
    "email address",
    "mail address",
    "electronic mail",
    "email id",
  ],
  phone: [
    "phone",
    "mobile",
    "mobile number",
    "cell",
    "cellphone",
    "contact number",
    "whatsapp number",
    "telephone",
    "tel",
    "phone number",
    "daytime phone",
    "evening phone",
  ],
  dateOfBirth: [
    "dob",
    "date of birth",
    "birth date",
    "birthday",
    "born",
    "age",
  ],
  gender: ["gender", "sex"],
  nationality: ["nationality", "citizenship", "country of citizenship"],
  languages: ["languages", "languages spoken", "language proficiency"],

  // Address
  address: [
    "address",
    "street",
    "home address",
    "line address",
    "street address",
    "residential address",
    "current address",
    "mailing address",
    "permanent address",
  ],
  city: ["city", "town", "municipality"],
  state: ["state", "province", "region", "territory"],
  zipCode: [
    "zip",
    "zipcode",
    "postal code",
    "pin code",
    "pincode",
    "post code",
    "zip code",
  ],
  country: ["country", "nation", "country of residence"],

  // Professional
  currentRole: [
    "current role",
    "current position",
    "job title",
    "designation",
    "current job",
    "role",
    "title",
    "current designation",
  ],
  yearsOfExperience: [
    "experience",
    "years of experience",
    "work experience",
    "total experience",
    "professional experience",
    "experience in years",
    "overall experience",
  ],
  education: [
    "education",
    "qualification",
    "degree",
    "academics",
    "university",
    "college",
    "educational qualification",
    "highest education",
    "education level",
  ],
  certifications: [
    "certifications",
    "certification",
    "certificates",
    "professional certifications",
  ],
  previousCompanies: [
    "previous company",
    "past employer",
    "previous employer",
    "companies worked",
    "employment history",
  ],
  skills: [
    "skills",
    "skillset",
    "technical skills",
    "key skills",
    "relevant skills",
    "core competencies",
    "expertise",
    "proficient in",
  ],

  // URLs
  linkedin: [
    "linkedin",
    "linked in",
    "linkedin url",
    "linkedin profile",
    "linkedin link",
  ],
  github: ["github", "git hub", "github url", "github profile", "github link"],
  portfolio: [
    "portfolio",
    "website",
    "site url",
    "personal site",
    "portfolio url",
    "personal website",
    "online portfolio",
    "blog",
  ],
  twitter: ["twitter", "x handle", "twitter handle", "twitter url"],
  website: ["website", "personal website", "blog url"],

  // Preferences
  salary: [
    "salary",
    "ctc",
    "compensation",
    "expected salary",
    "current salary",
    "salary expectation",
    "expected ctc",
    "current ctc",
    "annual salary",
    "expected compensation",
  ],
  relocation: [
    "relocation",
    "willing to relocate",
    "move city",
    "open to relocation",
    "relocate",
    "willing to move",
    "ready to relocate",
  ],
  availability: [
    "availability",
    "available from",
    "notice period",
    "join",
    "start date",
    "available to join",
    "immediate joiner",
    "joining period",
  ],
  workType: [
    "work type",
    "work mode",
    "work preference",
    "remote",
    "hybrid",
    "onsite",
    "work arrangement",
    "preferred work mode",
  ],
};

export const SENSITIVE_PATTERNS = new Set([
  "ssn",
  "social security",
  "passport number",
  "passport no",
  "driver license",
  "drivers license",
  "national id",
  "aadhaar",
  "pan card",
  "credit card",
  "debit card",
  "card number",
  "cvv",
  "bank account",
  "routing number",
  "password",
  "account number",
]);

// ── Subjective question keywords ─────────────────────────────────────

export const SUBJECTIVE_KEYWORDS = [
  "why",
  "what",
  "how",
  "describe",
  "explain",
  "tell us",
  "tell me",
  "interest",
  "motivation",
  "passion",
  "goal",
  "objective",
  "strength",
  "weakness",
  "challenge",
  "story",
  "example",
  "situation",
  "background",
  "yourself",
  "about you",
  "about yourself",
  "proud",
  "achievement",
  "accomplish",
  "leadership",
  "teamwork",
  "conflict",
  "overcome",
  "learned",
  "contribute",
  "influence",
  "impact",
  "project",
  "experience",
  "career",
  "aspiration",
  "ambition",
];

// ── Profile key patterns for inference ───────────────────────────────

export const PROFILE_KEY_PATTERNS: Array<[RegExp, keyof UserData]> = [
  [/\b(email|e-?mail|mail)\b/i, "email"],
  [/\b(phone|mobile|contact\s*number|cell|telephone|tel)\b/i, "phone"],
  [/\b(name|full\s*name)\b/i, "name"],
  [/\b(linkedin|linked\s*in)\b/i, "linkedin"],
  [/\b(github)\b/i, "github"],
  [/\b(portfolio|website|blog)\b/i, "portfolio"],
  [/\b(address|street\s*address)\b/i, "address"],
  [/\b(city|town)\b/i, "city"],
  [/\b(state|province)\b/i, "state"],
  [/\b(zip|zipcode|postal|pincode|pin\s*code)\b/i, "zipCode"],
  [/\b(country|nation)\b/i, "country"],
  [/\b(salary|ctc|compensation)\b/i, "salary"],
  [/\b(availability|notice\s*period)\b/i, "availability"],
  [/\b(skills?$|skillset|expertise)\b/i, "skills"],
  [/\b(education|qualification|degree|university|college)\b/i, "education"],
  [/\b(experience|work\s*exp)\b/i, "yearsOfExperience"],
  [/\b(certification|certifications)\b/i, "certifications"],
];
